---
# Docker repo URL.
docker_repo_url: https://download.docker.com/linux

# Used only for Ubuntu.
docker_apt_release_channel: stable
docker_apt_repository: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] {{ docker_repo_url }}/ubuntu {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_gpg_key: "{{ docker_repo_url }}/ubuntu/gpg"

# Docker daemon options as a dict
docker_daemon_options:
  exec-opts: ["native.cgroupdriver=systemd"]
