
---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 192.168.42.10
      vars:
        kubernetes_role: master
        ansible_user: vagrant
        ansible_ssh_private_key_file: ../.vagrant/machines/default/virtualbox/private_key
    worker:
      hosts:
        k8s-1:
          ansible_host: 192.168.42.11
        k8s-2:
          ansible_host: 192.168.42.12
      vars:
        kubernetes_role: node
        ansible_user: vagrant
        ansible_ssh_private_key_file: ../.vagrant/machines/default/virtualbox/private_key
