---
kubernetes_packages:
  - name: "kubelet={{ kubernetes_version }}-00"
    state: present
  - name: "kubectl={{ kubernetes_version }}-00"
    state: present
  - name: "kubeadm={{ kubernetes_version }}-00"
    state: present
  # - name: kubernetes-cni
  #   state: present

kubernetes_version: '1.22.2'

# Kubernetes repo URL.
kubernetes_repo_url: https://mirrors.ustc.edu.cn/kubernetes/apt/

keyring_path: /usr/share/keyrings/kubernetes-archive-keyring.gpg

# Used only for Ubuntu.
kubernetes_apt_repository: "deb [signed-by={{ keyring_path }}] {{ kubernetes_repo_url }}/ubuntu kubernetes-xenial main  "
kubernetes_apt_gpg_key: https://repo.huaweicloud.com/kubernetes/apt/doc/apt-key.gpg

kubernetes_kubeadm_init_extra_opts: ""
kubernetes_allow_pods_on_master: false
kubernetes_pod_network:
  # Flannel CNI.
  # cni: 'flannel'
  # cidr: '10.244.0.0/16'
  # Calico CNI.
  cni: 'calico'
  cidr: '192.168.0.0/16'

kubernetes_kubeadm_kubelet_config_file_path: '/etc/kubernetes/kubeadm-kubelet-config.yaml'
kubernetes_config_kubelet_configuration:
  cgroupDriver: "systemd"

kubernetes_config_init_configuration:
  localAPIEndpoint:
    advertiseAddress: "{{ kubernetes_apiserver_advertise_address | default(ansible_default_ipv4.address, true) }}"
# if you use the next lines, remove the command line argument below
# nodeRegistration:
#    ignorePreflightErrors:
#      - all

kubernetes_config_cluster_configuration:
  networking:
    podSubnet: "{{ kubernetes_pod_network.cidr }}"
  kubernetesVersion: "{{ kubernetes_version_kubeadm }}"

kubernetes_config_kube_proxy_configuration: {}

kubernetes_apiserver_advertise_address: ''
kubernetes_version_kubeadm: 'stable-{{ kubernetes_version }}'
kubernetes_ignore_preflight_errors: 'all'

# Flannel config files.
kubernetes_flannel_manifest_file_rbac: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml
kubernetes_flannel_manifest_file: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

# Calico config files
kubernetes_calico_manifest_file: https://docs.projectcalico.org/v3.20.2/manifests/calico.yaml
